
[webservers]


vm-web-1 ansible_host=34.101.150.154 private_ip=10.184.0.7


vm-web-2 ansible_host=34.101.165.55 private_ip=10.184.0.8



[dnsservers]


vm-dns-1 ansible_host=34.101.146.174 private_ip=10.184.0.9



[dbservers]


vm-db-1 ansible_host=34.101.135.180 private_ip=10.184.0.11



[all:vars]

ansible_user=dandy

ansible_ssh_private_key_file=/home/dandy/.ssh/google_compute_engine

ansible_python_interpreter=/usr/bin/python3

ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
