
[webservers]


vm-web-1 ansible_host=34.101.99.79 private_ip=10.184.0.15


vm-web-2 ansible_host=34.128.74.55 private_ip=10.184.0.16



[dnsservers]


vm-dns-1 ansible_host=34.50.109.125 private_ip=10.184.0.18



[dbservers]


vm-db-1 ansible_host=34.101.114.134 private_ip=10.184.0.21



[all:vars]

ansible_user=dandy

ansible_ssh_private_key_file=/home/dandy/.ssh/google_compute_engine

ansible_python_interpreter=/usr/bin/python3

ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
